[advisories]
unmaintained = "workspace"
ignore = [
]

[bans]
multiple-versions = "deny"
wildcards = 'deny'
deny = [
    { crate = "openssl", use-instead = "rustls" },
    { crate = "openssl-sys", use-instead = "rustls" },
    "libssh2-sys",
]
skip-tree = [
    { crate = "windows-sys", reason = "a foundational crate for many that bumps far too frequently to ever have a shared version" },
    { crate = "wasi", reason = "multiple versions pulled in by different dependencies" },
]

[licenses]
allow = [
    "Apache-2.0",
    "BSD-3-Clause",
    "MIT",
    "Unicode-3.0"
]

[sources]
unknown-git = "deny"
unknown-registry = "deny"
