name: kobo-library-sync-${PWD:?}

services:
  devcontainer:
    image: ghcr.io/dlrobson/kobo-library-sync-ci:latest
    group_add:
      - ${DOCKER_GID:?}
    volumes:
      - ..:/workspaces/kobo-library-sync:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: "bash -c 'trap exit TERM; sleep infinity & wait;'"
