name: kobo-library-sync-${PWD:?}

services:
  devcontainer:
    image: ghcr.io/dlrobson/kobo-library-sync:latest
    pull_policy: always
    volumes:
      - ..:/workspaces/kobo-library-sync:cached
    command: "bash -c 'trap exit TERM; sleep infinity & wait;'"
